<a href="https://colab.research.google.com/github/20JR1A4443/House/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [ ]:
import numpy as np
a = np.array ([1,2,3])
b = np.array ([(1.5,2,3), (4,5,6)],dtype = float)
c = np.array ([[(1.5,2,3), (4,5,6)],[(3,2,1), (4,5,6)]],dtype = float)
print (a)
print (b)
print (c)

[1 2 3]
[[1.5 2.  3. ]
 [4.  5.  6. ]]
[[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  2.  1. ]
  [4.  5.  6. ]]]


In [ ]:
# initial place holders
np.zeros ((9,3,4))


array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
np.ones ((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
d = np.arange(10,25,3)
print (d)

[10 13 16 19 22]


In [ ]:
np.linspace (0,2,99)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ,
       1.02040816, 1.04081633, 1.06122449, 1.08163265, 1.10204082,
       1.12244898, 1.14285714, 1.16326531, 1.18367347, 1.20408163,
       1.2244898 , 1.24489796, 1.26530612, 1.28571429, 1.30612245,
       1.32653061, 1.34693878, 1.36734694, 1.3877551 , 1.40816327,
       1.42857143, 1.44897959, 1.46938776, 1.48979592, 1.51020

In [ ]:
jai = np.full((6,9),9)
print (jai)

[[9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9]]


In [ ]:
jai = np.full((5,9,9),43)
print (jai)

[[[43 43 43 43 43 43 43 43 43]
  [43 43 43 43 43 43 43 43 43]
  [43 43 43 43 43 43 43 43 43]
  [43 43 43 43 43 43 43 43 43]
  [43 43 43 43 43 43 43 43 43]
  [43 43 43 43 43 43 43 43 43]
  [43 43 43 43 43 43 43 43 43]
  [43 43 43 43 43 43 43 43 43]
  [43 43 43 43 43 43 43 43 43]]

 [[43 43 43 43 43 43 43 43 43]
  [43 43 43 43 43 43 43 43 43]
  [43 43 43 43 43 43 43 43 43]
  [43 43 43 43 43 43 43 43 43]
  [43 43 43 43 43 43 43 43 43]
  [43 43 43 43 43 43 43 43 43]
  [43 43 43 43 43 43 43 43 43]
  [43 43 43 43 43 43 43 43 43]
  [43 43 43 43 43 43 43 43 43]]

 [[43 43 43 43 43 43 43 43 43]
  [43 43 43 43 43 43 43 43 43]
  [43 43 43 43 43 43 43 43 43]
  [43 43 43 43 43 43 43 43 43]
  [43 43 43 43 43 43 43 43 43]
  [43 43 43 43 43 43 43 43 43]
  [43 43 43 43 43 43 43 43 43]
  [43 43 43 43 43 43 43 43 43]
  [43 43 43 43 43 43 43 43 43]]

 [[43 43 43 43 43 43 43 43 43]
  [43 43 43 43 43 43 43 43 43]
  [43 43 43 43 43 43 43 43 43]
  [43 43 43 43 43 43 43 43 43]
  [43 43 43 43 43 43 43 43 43]
  

In [ ]:
jai = np.eye(9)
print (jai)

[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [ ]:
np.random.random((2,5,6))

array([[[0.75164298, 0.05103648, 0.96335373, 0.73146218, 0.59766808,
         0.22814275],
        [0.17550778, 0.87583048, 0.98849951, 0.31537434, 0.35857278,
         0.94480697],
        [0.13626585, 0.18401776, 0.41100545, 0.87594846, 0.29881209,
         0.57183544],
        [0.02011399, 0.56691283, 0.25487023, 0.89736732, 0.25004101,
         0.29832732],
        [0.01218814, 0.17201366, 0.96652939, 0.7528144 , 0.96038509,
         0.21335414]],

       [[0.82695968, 0.00538294, 0.40774234, 0.27627585, 0.31502847,
         0.80077103],
        [0.0053402 , 0.87838587, 0.7120968 , 0.0126604 , 0.55688435,
         0.3219885 ],
        [0.01530585, 0.84015481, 0.17797107, 0.58264683, 0.8999153 ,
         0.28882418],
        [0.42815887, 0.61472565, 0.59417607, 0.21152511, 0.94300801,
         0.4891965 ],
        [0.19074422, 0.76370663, 0.19373589, 0.26910407, 0.96862327,
         0.70318762]]])

In [15]:
# to find shape of an array
arr = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(arr.shape)

(3, 3)


In [16]:
# to find number of elements in array
jai = np.array([[1,2,3],
                [4,5,6],
                [1,2,1]])
print(jai.size)

9


In [17]:
# to find length of an array
jai = np.array([[1,2,3],
                [4,5,6],
                [1,2,1]])
print(len(jai))

3


In [3]:
# Access array elements
arr = np.array ([1,2,3,4])
print(arr[2])

3


In [4]:
# adding two index position
arr = np.array ([1,1,1,2,2,2,3,4,5])
print(arr[5]+arr[7]-arr[4])

4


In [6]:
arr = np.array ([[1,2,3,4,5],
                 [6,7,8,9,10],
                 [6,7,5,9,10],
                 [6,7,8,9,1]])
print(arr[3,4])

1


In [13]:
arr = np.array([[[1,2,3],[4,5,6]],
                 [[7,8,9],[10,11,12]],
                 [[13,14,15],[16,17,18]]])
print(arr[1,1,1])

11


In [15]:
arr = np.array ([1,2,3],dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3']
|S1


In [17]:
arr = np.array ([1,9,2,5],dtype='i')
print(arr)
print(arr.dtype)

[1 9 2 5]
int32


In [18]:
arr = np.array ([1.1,2.5,3.8],dtype='i')
print(arr)
print(arr.dtype)

[1 2 3]
int32


In [21]:
arr = np.array ([1,0,6,7],dtype='bool')
print(arr)
print(arr.dtype)

[ True False  True  True]
bool


In [22]:
arr = np.array([11,99,22,88,55])
jai= arr.copy()
arr[0]=111
print(arr)
print(jai)


[111  99  22  88  55]
[11 99 22 88 55]


In [23]:
arr = np.array([11,99,22,88,55])
jai= arr.view()
arr[0]=43
print(arr)
print(jai)

[43 99 22 88 55]
[43 99 22 88 55]


In [26]:
arr = np.array([[12,13,22,35],
               [1,2,3,4]])
print(arr.shape)

(2, 4)


In [29]:
# Reshaping arrays
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr.size)
newarr=arr.reshape(2,6)
print(newarr)

12
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [31]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(2,2,3)
print(newarr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [2]:
x = np.array([[1,2],[3,4]],dtype=np.float64)
y = np.array([[5,6],[7,8]],dtype=np.float64)


In [3]:
print(x+y)
print(np.add(x,y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [5]:
print(x-y)
print(np.subtract(x,y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [6]:
print(x*y)
print(np.multiply(x,y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [7]:
print(x/y)
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [8]:
print(x%y)
print(np.remainder(x,y))

[[1. 2.]
 [3. 4.]]
[[1. 2.]
 [3. 4.]]


In [9]:
print(x%y)
print(np.remainder(x,y))

[[0. 0.]
 [0. 0.]]
[[0. 0.]
 [0. 0.]]


In [11]:
print(x**y)
print(np.exponetial(x,y))

[[1.0000e+00 6.4000e+01]
 [2.1870e+03 6.5536e+04]]


AttributeError: module 'numpy' has no attribute 'exponetial'

In [13]:
x = np.array([[1,2],[3,4],
              [5,6],[7,8]])
y = np.array([[15,16],[17,18],
              [11,12],[13,14]])


In [14]:
print(x+y)
print(np.add(x,y))

[[16 18]
 [20 22]
 [16 18]
 [20 22]]
[[16 18]
 [20 22]
 [16 18]
 [20 22]]


In [15]:
print(x-y)
print(np.subtract(x,y))

[[-14 -14]
 [-14 -14]
 [ -6  -6]
 [ -6  -6]]
[[-14 -14]
 [-14 -14]
 [ -6  -6]
 [ -6  -6]]


In [16]:
print(x*y)
print(np.multiply(x,y))

[[ 15  32]
 [ 51  72]
 [ 55  72]
 [ 91 112]]
[[ 15  32]
 [ 51  72]
 [ 55  72]
 [ 91 112]]


In [17]:
print(x/y)
print(np.divide(x,y))

[[0.06666667 0.125     ]
 [0.17647059 0.22222222]
 [0.45454545 0.5       ]
 [0.53846154 0.57142857]]
[[0.06666667 0.125     ]
 [0.17647059 0.22222222]
 [0.45454545 0.5       ]
 [0.53846154 0.57142857]]


In [18]:
print(x%y)
print(np.remainder(x,y))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [19]:
print(x**y)
print(np.exponetial(x,y))

[[            1         65536]
 [    129140163   68719476736]
 [     48828125    2176782336]
 [  96889010407 4398046511104]]


AttributeError: module 'numpy' has no attribute 'exponetial'